name: Notify Telegram Channel on Push to Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Telegram Channel
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.CHANEL_ID }} \
          -d text="🚀 A new push was made to the main branch in repository [${{ github.repository }}](https://github.com/${{ github.repository }}) by [${{ github.actor }}](https://github.com/${{ github.actor }}). Commit message: *${{ github.event.head_commit.message || 'No commit message provided' }}*. You can view the changes made in this commit [here](https://github.com/${{ github.repository }}/commit/${{ github.event.head_commit.id }})." \
          -d parse_mode=Markdown
